"""Initial migration

Revision ID: 17745399b419
Revises: 
Create Date: 2025-03-27 22:19:57.361922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17745399b419'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор задачи'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание задачи'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='Флаг выполненности задачи'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
